######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 23 08:39:14 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              gui \
              Resources \
              gui/ChanceTreeView \
              gui/PuzzleView \
              gui/TreeView \
              gui/ChanceTreeView/GraphView \
              gui/ChanceTreeView/TraceView \
              gui/PuzzleView/GraphView \
              gui/PuzzleView/TraceView \
              gui/TreeView/GraphView \
              gui/TreeView/TraceView \
              gui/ChanceTreeView/TraceView/TreeTracers \
              gui/PuzzleView/TraceView/PuzzleTracers \
              gui/TreeView/TraceView/TreeTracers
INCLUDEPATH += . \
               gui \
               gui/PuzzleView \
               gui/TreeView \
               gui/ChanceTreeView \
               gui/ChanceTreeView/GraphView \
               gui/ChanceTreeView/TraceView \
               gui/ChanceTreeView/TraceView/TreeTracers \
               gui/PuzzleView/GraphView \
               gui/PuzzleView/TraceView \
               gui/TreeView/GraphView \
               gui/TreeView/TraceView \
               gui/TreeView/TraceView/TreeTracers \
               gui/PuzzleView/TraceView/PuzzleTracers

# Input
HEADERS += gnat.h \
           gui/CEditStyleToolkit.h \
           gui/CGNATWindow.h \
           gui/CStyleToolkit.h \
           gui/IGNATView.h \
           gui/ChanceTreeView/CChanceTreeGraph.h \
           gui/ChanceTreeView/CChanceTreeView.h \
           gui/ChanceTreeView/SChanceTreeTrace.h \
           gui/PuzzleView/CPuzzleGraph.h \
           gui/PuzzleView/CPuzzleTrace.h \
           gui/PuzzleView/CPuzzleView.h \
           gui/TreeView/CTreeGraph.h \
           gui/TreeView/CTreeView.h \
           gui/TreeView/STreeTrace.h \
           gui/ChanceTreeView/GraphView/CChanceTreeGraphModel.h \
           gui/ChanceTreeView/GraphView/CChanceTreeGraphView.h \
           gui/ChanceTreeView/GraphView/CChanceTreeHistoryArtist.h \
           gui/ChanceTreeView/GraphView/CChanceTreeNodeArtist.h \
           gui/ChanceTreeView/GraphView/CChanceTreeNodeEditor.h \
           gui/ChanceTreeView/GraphView/CChanceTreeNodeMover.h \
           gui/ChanceTreeView/GraphView/CChanceTreeNodeQuickEditor.h \
           gui/ChanceTreeView/TraceView/CChanceTreeTraceView.h \
           gui/PuzzleView/GraphView/CPuzzleGraphModel.h \
           gui/PuzzleView/GraphView/CPuzzleGraphView.h \
           gui/PuzzleView/GraphView/CPuzzleNodeArtist.h \
           gui/PuzzleView/GraphView/CPuzzleNodeCreator.h \
           gui/PuzzleView/GraphView/CPuzzleNodeEditor.h \
           gui/PuzzleView/GraphView/CPuzzleNodeMover.h \
           gui/PuzzleView/GraphView/CPuzzleSpanArtist.h \
           gui/PuzzleView/GraphView/CPuzzleSpanCreator.h \
           gui/PuzzleView/GraphView/CPuzzleSpanEditor.h \
           gui/PuzzleView/TraceView/CPuzzleTraceModel.h \
           gui/PuzzleView/TraceView/CPuzzleTraceView.h \
           gui/TreeView/GraphView/CTreeGraphModel.h \
           gui/TreeView/GraphView/CTreeGraphView.h \
           gui/TreeView/GraphView/CTreeHistoryArtist.h \
           gui/TreeView/GraphView/CTreeNodeArtist.h \
           gui/TreeView/GraphView/CTreeNodeEditor.h \
           gui/TreeView/GraphView/CTreeNodeMover.h \
           gui/TreeView/GraphView/CTreeNodeQuickEditor.h \
           gui/TreeView/TraceView/CTreeTraceView.h \
           gui/ChanceTreeView/TraceView/TreeTracers/CChanceTreeTracerSelector.h \
           gui/ChanceTreeView/TraceView/TreeTracers/CExpectMTracer.h \
           gui/PuzzleView/TraceView/PuzzleTracers/CBDTracer.h \
           gui/PuzzleView/TraceView/PuzzleTracers/CPuzzleTracerSelector.h \
           gui/PuzzleView/TraceView/PuzzleTracers/CSATraceNode.h \
           gui/PuzzleView/TraceView/PuzzleTracers/CUDTracer.h \
           gui/PuzzleView/TraceView/PuzzleTracers/IOpenList.h \
           gui/PuzzleView/TraceView/PuzzleTracers/IPuzzleTracer.h \
           gui/TreeView/TraceView/TreeTracers/CGeneralMTracer.h \
           gui/TreeView/TraceView/TreeTracers/CTreeTracerSelector.h
SOURCES += gnat.cpp \
           gui/CEditStyleToolkit.cpp \
           gui/CGNATWindow.cpp \
           gui/CStyleToolkit.cpp \
           gui/IGNATView.cpp \
           gui/ChanceTreeView/CChanceTreeGraph.cpp \
           gui/ChanceTreeView/CChanceTreeView.cpp \
           gui/ChanceTreeView/SChanceTreeTrace.cpp \
           gui/PuzzleView/CPuzzleGraph.cpp \
           gui/PuzzleView/CPuzzleTrace.cpp \
           gui/PuzzleView/CPuzzleView.cpp \
           gui/TreeView/CTreeGraph.cpp \
           gui/TreeView/CTreeView.cpp \
           gui/TreeView/STreeTrace.cpp \
           gui/ChanceTreeView/GraphView/CChanceTreeGraphModel.cpp \
           gui/ChanceTreeView/GraphView/CChanceTreeGraphView.cpp \
           gui/ChanceTreeView/GraphView/CChanceTreeHistoryArtist.cpp \
           gui/ChanceTreeView/GraphView/CChanceTreeNodeArtist.cpp \
           gui/ChanceTreeView/GraphView/CChanceTreeNodeEditor.cpp \
           gui/ChanceTreeView/GraphView/CChanceTreeNodeMover.cpp \
           gui/ChanceTreeView/GraphView/CChanceTreeNodeQuickEditor.cpp \
           gui/ChanceTreeView/TraceView/CChanceTreeTraceView.cpp \
           gui/PuzzleView/GraphView/CPuzzleGraphModel.cpp \
           gui/PuzzleView/GraphView/CPuzzleGraphView.cpp \
           gui/PuzzleView/GraphView/CPuzzleNodeArtist.cpp \
           gui/PuzzleView/GraphView/CPuzzleNodeCreator.cpp \
           gui/PuzzleView/GraphView/CPuzzleNodeEditor.cpp \
           gui/PuzzleView/GraphView/CPuzzleNodeMover.cpp \
           gui/PuzzleView/GraphView/CPuzzleSpanArtist.cpp \
           gui/PuzzleView/GraphView/CPuzzleSpanCreator.cpp \
           gui/PuzzleView/GraphView/CPuzzleSpanEditor.cpp \
           gui/PuzzleView/TraceView/CPuzzleTraceModel.cpp \
           gui/PuzzleView/TraceView/CPuzzleTraceView.cpp \
           gui/TreeView/GraphView/CTreeGraphModel.cpp \
           gui/TreeView/GraphView/CTreeGraphView.cpp \
           gui/TreeView/GraphView/CTreeHistoryArtist.cpp \
           gui/TreeView/GraphView/CTreeNodeArtist.cpp \
           gui/TreeView/GraphView/CTreeNodeEditor.cpp \
           gui/TreeView/GraphView/CTreeNodeMover.cpp \
           gui/TreeView/GraphView/CTreeNodeQuickEditor.cpp \
           gui/TreeView/TraceView/CTreeTraceView.cpp \
           gui/ChanceTreeView/TraceView/TreeTracers/CChanceTreeTracerSelector.cpp \
           gui/ChanceTreeView/TraceView/TreeTracers/CExpectMTracer.cpp \
           gui/PuzzleView/TraceView/PuzzleTracers/CBDTracer.cpp \
           gui/PuzzleView/TraceView/PuzzleTracers/CPuzzleTracerSelector.cpp \
           gui/PuzzleView/TraceView/PuzzleTracers/CUDTracer.cpp \
           gui/PuzzleView/TraceView/PuzzleTracers/IOpenList.cpp \
           gui/PuzzleView/TraceView/PuzzleTracers/IPuzzleTracer.cpp \
           gui/TreeView/TraceView/TreeTracers/CGeneralMTracer.cpp \
           gui/TreeView/TraceView/TreeTracers/CTreeTracerSelector.cpp
RESOURCES += Resources/gnat.qrc
